name: Help me
description: Get help with WhereDoIHaveAnAccount
title: "Help me:"
labels: help wanted
body:
  - type: markdown
    attributes:
      value: Thanks for using WhereDoIHaveAnAccount!
  - type: textarea
    id: description
    attributes:
      label: Describe
      description: A clear and concise description.
    validations:
      required: true
