name: Build

on: [push]

jobs:

  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: pyinstaller -F -w -n WhereDoIHaveAnAccount --add-data "gui/assets/*.png;gui/assets" run.py
            OUT_FILE_NAME: WhereDoIHaveAnAccount.exe
            ASSET_MIME: application/vnd.microsoft.portable-executable
          - os: macos-latest
            TARGET: mac
            CMD_BUILD: pyinstaller -F -w -n WhereDoIHaveAnAccount --add-data "gui/assets/*.png;gui/assets" run.py
            OUT_FILE_NAME: WhereDoIHaveAnAccount.app
          - os: ubuntu-latest
            TARGET: linux
            CMD_BUILD: pyinstaller -F -n WhereDoIHaveAnAccount --add-data gui/assets/*.png:gui/assets run.py
            OUT_FILE_NAME: WhereDoIHaveAnAccount
            ASSET_MIME: application/x-executable
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build with pyinstaller for ${{matrix.TARGET}}
      run: ${{matrix.CMD_BUILD}}
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: automated-builds
        path: ./dist/${{ matrix.OUT_FILE_NAME}}
        retention-days: 7
        if-no-files-found: error